trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - job: Build_and_Test
    displayName: Build and Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build client image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
          $(tag)
    
    - task: Docker@2
      displayName: Build server image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/server/Dockerfile'
        tags: |
          $(tag)

    - script: |
        # Run client tests
        docker run --rm student-data-app-server-1 npm run test
      displayName: Run client tests

    - script: |
        # Run server tests
        docker run --rm student-data-app-server-1 npm run test
      displayName: Run server tests
