trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  client_image_name: ''
  server_image_name: ''

stages:
- stage: Build_and_Test
  displayName: Build and Test
  jobs:
  - job: Build_and_Test
    displayName: Build and Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build client image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
        tags: |
          $(tag)
    
    - script: |
        echo "##vso[task.setvariable variable=client_image_name]my_client_image:$(tag)"
      displayName: 'Set client image name'

    - task: Docker@2
      displayName: Build server image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/server/Dockerfile'
        tags: |
          $(tag)

    - script: |
        echo "##vso[task.setvariable variable=server_image_name]my_server_image:$(tag)"
      displayName: 'Set server image name'

    - script: |
        docker run --rm $(client_image_name) npm run test
      displayName: 'Run client tests'

    - script: |
        docker run --rm $(server_image_name) npm run test
      displayName: 'Run server tests'
